/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//Ext.Loader.setConfig({
//  enabled: true,
//  paths: {
//    'FlexMobile': './app'
//  }
//});

Ext.application({
//  models: [
//    'FlexMobile.model.FundingAccount',
//    'FlexMobile.model.Payment'
//  ],
//  stores: [
//    'FlexMobile.store.FundingAccounts',
//    'FlexMobile.store.HistoryPayments'
//  ],
//  views: [
//    'FlexMobile.view.FlexMobile',
//    'FlexMobile.view.Summary',
//    'FlexMobile.view.Payment',
//    'FlexMobile.view.History'
//  ],
  models: [
    'FundingAccount',
    'Payment'
  ],
  stores: [
    'FundingAccounts',
    'HistoryPayments'
  ],
  views: [
    'FlexMobile',
    'Summary',
    'Payment',
    'History'
  ],
  name: 'FlexMobile',

  launch: function() {

    Ext.create('FlexMobile.view.FlexMobile', {fullscreen: true});
  }

});
