/*
 * File: app/view/FlexMobile.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexMobile.view.FlexMobile', {
  extend: 'Ext.tab.Panel',

  requires: [
    'FlexMobile.view.Summary',
    'FlexMobile.view.Payment',
    'FlexMobile.view.History'
  ],

  config: {
    items: [
      {
        xtype: 'summary',
        title: flexMobileAppRes.summary,
        iconCls: 'home'
      },
      {
        xtype: 'payment',
        scrollable: 'vertical',
        title: flexMobileAppRes.payment,
        iconCls: 'action'
      },
      {
        xtype: 'history',
        title: flexMobileAppRes.history,
        iconCls: 'info'
      }
    ],
    tabBar: {
      docked: 'bottom'
    }
  }

});