/*
 * File: app/view/History.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexMobile.view.History', {
  extend:'Ext.Container',
  alias:'widget.history',

  requires:[
    'Ext.ux.touch.grid.List',
    'Ext.ux.touch.grid.feature.Feature',
    'Ext.ux.touch.grid.feature.Paging',
    'Ext.ux.touch.grid.feature.Sorter'
  ],

  config:{
    layout:'fit',
    items:[
      {
        xtype:'titlebar',
        docked:'top',
        title:flexMobileAppRes.paymentHistory
      },
      {
        xtype:'touchgridpanel',
        store:'HistoryPaymentStore',
        features:[
          {
            ftype:'Ext.ux.touch.grid.feature.Paging',
            launchFn:'initialize'
          },
          {
            ftype:'Ext.ux.touch.grid.feature.Sorter',
            launchFn:'initialize'
          }
        ],
        columns:[
          {
            header:'Payment Date',
            dataIndex:'paymentDate',
            width:'30%',
            renderer:function (value) {
              return Ext.Date.format(value, 'n/j/Y');
            }
          },
          {
            header:'Amount',
            dataIndex:'amount',
            style:'text-align: center;',
            width:'15%',
            filter:{ type:'numeric' }
          },
          {
            header:'Funding Account',
            dataIndex:'fundingAccount',
            width:'20%'
          },
          {
            header:'Status',
            dataIndex:'status',
            width:'20%'
          },
          {
            header:'Payment Offer',
            dataIndex:'paymentOffer',
            cls:'centered-cell',
            renderer:function (value) {
              return value ? 'Yes' : 'No';
            }
          }
        ]
      }
    ]
  }

});