/*
 * File: app/view/Summary.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexMobile.view.Summary', {
  extend: 'Ext.Container',
  alias: 'widget.summary',

  config: {
    border: 5,
    scrollable: 'vertical',
    items: [
      {
        xtype: 'titlebar',
        docked: 'top',
        title: flexMobileAppRes.accountSummary
      },
      {
        xtype: 'container',
        margin: 10,
        padding: '',
        items: [
          {
            html: [flexMobileAppRes.vLastUpdate]
          },
          {
            xtype: 'fieldset',
            title: flexMobileAppRes.currentAccountInformation,
            items: [
              {
                xtype: 'textfield',
                label: 'Balance',
                labelWidth: '40%',
                name: 'balance',
                value: flexMobileAppRes.vBalance,
                readOnly: true
              },
              {
                xtype: 'textfield',
                label: flexMobileAppRes.totalDue,
                labelWidth: '40%',
                name: 'totalDue',
                value: flexMobileAppRes.vTotalDue,
                readOnly: true
              },
              {
                xtype: 'textfield',
                label: flexMobileAppRes.pastDue,
                labelWidth: '40%',
                name: 'pastDue',
                value: flexMobileAppRes.vPastDue,
                readOnly: true
              }
            ]
          },
          {
            xtype: 'fieldset',
            title: flexMobileAppRes.paymentInformation,
            items: [
              {
                xtype: 'textfield',
                label: flexMobileAppRes.paymentDueDate,
                labelWidth: '40%',
                name: 'paymentDueDate',
                value: flexMobileAppRes.vPaymentDate,
                readOnly: true
              },
              {
                xtype: 'textfield',
                label: flexMobileAppRes.lastPaymentAmount,
                labelWidth: '40%',
                name: 'lastPayAmount',
                value: flexMobileAppRes.vLastPayAmount,
                readOnly: true
              },
              {
                xtype: 'textfield',
                label: flexMobileAppRes.lastPaymentDate,
                labelWidth: '40%',
                name: 'lastPayDate',
                value: flexMobileAppRes.vLastPayDate,
                readOnly: true
              }
            ]
          }
        ]
      }
    ]
  }

});