/*
 * File: app/store/HistoryPayments.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FlexMobile.store.HistoryPayments', {
  extend: 'Ext.data.Store',

  requires: [
    'FlexMobile.model.Payment'
  ],

  config: {
    autoLoad: true,
    model: 'FlexMobile.model.Payment',
    storeId: 'HistoryPaymentStore',
    sorters : [
      {
        property  : 'paymentDate',
        direction : 'DESC'
      }
    ],
    proxy: {
      type: 'ajax',
      url: flexMobileAppRes.urlHistoryPayment,
      reader: {
        type: 'json',
        totalProperty: 'total',
        rootProperty: 'root'
      }
    }
  }
});